### ISSUE TITLE
Default Rouge AP and default Evil Portal

### ISSUE THREAD

**Issue by krisss117** [Cancro29/NETHERCAP#18]
I think it is a mistake. 

When select DEFAULT on Evil Portal when i see Route AP page.

Please add DEFAULT for Evil Portal and DEFAULT for Rouge AP.

![image](https://github.com/Cancro29/NETHERCAP/assets/66109831/f298102e-3eb0-41a5-84c8-44bdacca130d)

**Comment by Cancro29** [comment]
It is a bug. HTML preview can become unconsistent sometimes but it does not affect anything. You can re-click the button to refresh it.
I don't provide default Rogue AP page because Rogue AP come in different variants. I can't provide generic Rogue AP page because it will be useless for most people, and I also can't provide login page for commercial product's login page (example: social media) as default Rogue AP page.
